module.exports = {
	NAME_DIV: '.content > table:nth-child(2) > tr > td > div',
	PRINT_A: '.content > div > a',
	METAL_A: '.content > table:nth-child(10) > tr:nth-child(2) > td:nth-child(2) > a',
	DENOMINATION_A: '.content > table:nth-child(10) > tr:nth-child(2) > td:nth-child(1) > a',
	DATE_TD: '.content > table:nth-child(9) > tr:nth-child(1) > td',
	WEIGHT_TD: '.content > table:nth-child(10) > tr:nth-child(2) > td:nth-child(3)',
	DIAMETER_A: '.content > table:nth-child(10) > tr:nth-child(2) > td:nth-child(4) > a',
	THICKNESS_TD: '.content > table:nth-child(10) > tr:nth-child(2) > td:nth-child(5)',
	QUALITY_A: '.content > table:nth-child(10) > tr:nth-child(2) > td:nth-child(5) > a',
	QUALITY_A_WITH_THICKNESS: '.content > table:nth-child(10) > tr:nth-child(2) > td:nth-child(6) > a',
	EDGE_A: '.content > table:nth-child(10) > tr:nth-child(2) > td:nth-child(6)',
	EDGE_A_WITH_THICKNESS: '.content > table:nth-child(10) > tr:nth-child(2) > td:nth-child(7)',
	MINTAGE_TD: '.content > table:nth-child(10) > tr:nth-child(2) > td:nth-child(7)',
	MINTAGE_TD_WITH_THICKNESS: '.content > table:nth-child(10) > tr:nth-child(2) > td:nth-child(8)',
	CATEGORY_A: '.content > table:nth-child(12) > tr:nth-child(1) > td > a',
	GENERAL_DESCRIPTION_TD: '.content > table:nth-child(12) > tr:nth-child(2) > td',
	AVERSE_DESCRIPTION_TD: '.content > table:nth-child(12) > tr:nth-child(4) > td > table > tr:nth-child(1) > td.coin',
	REVERSE_DESCRIPTION_TD: '.content > table:nth-child(12) > tr:nth-child(4) > td > table > tr:nth-child(2) > td.coin',
	TECH_TD: '.content > table:nth-child(10) > tr:nth-child(1) > td'
};